import type { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Vaso Rústico Esmaltado",
    cat: "Cerâmica",
    desc: "Peça única com esmalte terra-cotta e acabamento artesanal",
    price: 74.9,
    original: 89,
    emoji: "🏺",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 2,
    name: "Tigela de Argila Branca",
    cat: "Cerâmica",
    desc: "Ideal para servir petiscos ou decoração, textura natural",
    price: 49.9,
    emoji: "🥣",
    inStock: true,
  },
  {
    id: 3,
    name: "Xícara Minimalista",
    cat: "Cerâmica",
    desc: "Conjunto com pires, acabamento acetinado em bege",
    price: 65,
    original: 80,
    emoji: "☕",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 4,
    name: "Prato Rústico Fundo",
    cat: "Cerâmica",
    desc: "Argila refratária, vai ao forno e é microondas-safe",
    price: 58,
    emoji: "🍽️",
    badge: "Novo",
    inStock: true,
  },
  {
    id: 5,
    name: "Jarro de Boca Larga",
    cat: "Cerâmica",
    desc: "Perfeito para flores secas ou como peça decorativa",
    price: 92,
    emoji: "🫙",
    inStock: true,
  },
  {
    id: 6,
    name: "Porta-Incenso Artesanal",
    cat: "Cerâmica",
    desc: "Suporte com detalhes entalhados à mão",
    price: 35,
    emoji: "🕯️",
    badge: "Último",
    inStock: true,
  },
  {
    id: 7,
    name: "Tapete Boho Bege",
    cat: "Macramê",
    desc: "100% algodão cru, 60×40 cm, nós artesanais",
    price: 129,
    emoji: "🧶",
    badge: "Novo",
    inStock: true,
  },
  {
    id: 8,
    name: "Porta-Vaso Suspenso",
    cat: "Macramê",
    desc: "Triplo, suporta vasos até 18 cm de diâmetro",
    price: 89,
    original: 110,
    emoji: "🪴",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 9,
    name: "Mandala de Parede",
    cat: "Macramê",
    desc: "Diâmetro 50 cm, algodão trançado com detalhes naturais",
    price: 149,
    emoji: "🌀",
    inStock: true,
  },
  {
    id: 10,
    name: "Porta-Chaves Decorativo",
    cat: "Macramê",
    desc: "Pequeno painel para entrada, inclui 5 ganchos de madeira",
    price: 62,
    emoji: "🔑",
    inStock: true,
  },
  {
    id: 11,
    name: "Vela de Soja — Lavanda",
    cat: "Velas",
    desc: "Fragrância floral duradoura, burn time ~40h, cera vegana",
    price: 42,
    emoji: "💜",
    badge: "Novo",
    inStock: true,
  },
  {
    id: 12,
    name: "Vela Rústica de Cera de Abelha",
    cat: "Velas",
    desc: "Aroma natural suave, molde de bambu, 100% natural",
    price: 38,
    emoji: "🕯️",
    inStock: true,
  },
  {
    id: 13,
    name: "Trio de Votivas Amadeiradas",
    cat: "Velas",
    desc: "Notas de cedro, patchouli e vetiver — burn time ~15h cada",
    price: 55,
    original: 65,
    emoji: "🔥",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 14,
    name: "Vela Terapêutica Eucalipto",
    cat: "Velas",
    desc: "Óleos essenciais puros, ideal para meditação",
    price: 48,
    emoji: "🌿",
    inStock: true,
  },
  {
    id: 15,
    name: "Tábua de Servir Rústica",
    cat: "Madeira",
    desc: "Madeira de lei reaproveitada, 35×20 cm, com alça",
    price: 95,
    emoji: "🪵",
    badge: "Novo",
    inStock: true,
  },
  {
    id: 16,
    name: "Porta-Temperos de Pinus",
    cat: "Madeira",
    desc: "6 potes de vidro inclusos, estrutura artesanal vernizada",
    price: 138,
    emoji: "🧂",
    inStock: true,
  },
  {
    id: 17,
    name: "Porta-Retrato Boho",
    cat: "Madeira",
    desc: "Moldura de galho natural, 10×15 cm, peça única",
    price: 52,
    emoji: "🖼️",
    inStock: true,
  },
  {
    id: 18,
    name: "Fruteira Trançada",
    cat: "Madeira",
    desc: "Junco e bambu, redonda, 30 cm de diâmetro",
    price: 78,
    original: 95,
    emoji: "🧺",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 19,
    name: "Sabonete de Argila Rosa",
    cat: "Sabonetes",
    desc: "100g, esfoliante suave, perfume floral delicado",
    price: 22,
    emoji: "🌸",
    badge: "Novo",
    inStock: true,
  },
  {
    id: 20,
    name: "Barra de Aveia e Mel",
    cat: "Sabonetes",
    desc: "Hidratante, ideal para pele seca, 120g",
    price: 24,
    emoji: "🍯",
    inStock: true,
  },
  {
    id: 21,
    name: "Kit Spa 3 Sabonetes",
    cat: "Sabonetes",
    desc: "Lavanda, menta e aloe vera — embalagem presente inclusa",
    price: 62,
    original: 72,
    emoji: "🧼",
    badge: "Oferta",
    inStock: true,
  },
  {
    id: 22,
    name: "Sabonete de Carvão Ativado",
    cat: "Sabonetes",
    desc: "Limpeza profunda, matte, aroma amadeirado seco",
    price: 28,
    emoji: "🖤",
    inStock: true,
  },
];

export const categories = [
  "Todos",
  ...Array.from(new Set(products.map((p) => p.cat))),
];
